name: starpath
description: Proyecto final Juan XXIII
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dotenv: 4.2.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  flutter_mailer: ^2.1.2
  intl: ^0.19.0
  mailer: ^6.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  supabase: ^2.0.8  
  supabase_auth_ui: ^0.4.3
  uuid: ^3.0.4
  flutter_keyboard_visibility: ^5.0.0
  carousel_slider: ^4.2.1
  image_cropper: ^5.0.1
  image_picker: ^0.8.4+3
  http: 1.2.0
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

