name: starpath
description: Proyecto final Juan XXIII
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dotenv: 4.2.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  supabase: ^2.0.8  
  supabase_auth_ui: ^0.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

